from tkinter import *
import mysql.connector
root=Tk()
con=mysql.connector.connect(host='localhost',user='root',password='1234',database='python_bus')
cur=con.cursor()
cur.execute('select max(Reference_Id) from Booking_history')
a=cur.fetchall()
cur.execute('select Name,Phone,Age,Gender,Boarding,Upto,Travelling_Date,Booking_date,Seates_booked,Bus_Id,fare,reference_id from booking_history where reference_id={}'.format(a[0][0]))
res=cur.fetchall()
(h,w)=root.winfo_screenwidth(),root.winfo_screenheight()
root.geometry('%dx%d+0+0'%(h,w))
bus= PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=bus).grid(column=0,row=0,columnspan=10,padx=600)
Label(root,text='Online Bus Booking System',bg='lightblue',fg='red',font='Arial 20 bold').grid(row=1,column=0,columnspan=10,padx=w/2,pady=20)
Label(root, text ="Bus Ticket",font='Arial 10 bold').grid(row=2,column=0,columnspan=10,padx=10,pady=20)
final = LabelFrame(root)
final.grid(row=8,column=2,padx=600)
Label(final, text = "Passenger: {}".format(res[0][0])).grid(row =8, column=0)
Label(final, text = "No of seats: {}".format(res[0][8])).grid(row =9, column=0)
Label(final, text = "Age: {}".format(res[0][2])).grid(row =10, column=0)
Label(final, text = "Booking Ref. {}".format(res[0][11])).grid(row =11, column=0)
Label(final, text = "Travels on: {}".format(res[0][6])).grid(row =12, column=0)
Label(final, text = "Gender: {}".format(res[0][3])).grid(row =8, column=1)
Label(final, text = "Phone: {}".format(res[0][1])).grid(row =9, column=1)
Label(final, text = "Fare Rs: {}".format(res[0][10])).grid(row =10, column=1)
Label(final, text = "Booked On: {}".format(res[0][7])).grid(row =11, column=1)
Label(final, text = "Boarding Point: {}".format(res[0][4])).grid(row =12, column=1)
Label(final, text = "").grid(row =13,column=1)
Label(final, text = "Total amount Rs {} to be paid at the time of boarding the bus".format(res[0][10]),fg='grey').grid(row =14, column=0,columnspan=2)
root.mainloop()
